# Top-level configuration
name = "riils-site"
main = "src/_worker.ts"/Users/braianmellor/Work/Decentraland/landing/tsconfig.worker.json
compatibility_date = "2023-03-14"
send_metrics = false

workers_dev = false
route = { pattern = "decentraland.zone/*", zone_name = "decentraland.zone" }
tsconfig = "./tsconfig.worker.json"
