export enum SegmentImage {
  Share = "Share",
  CopyLink = "Copy Link",
  Download = "Download",
  JumpIn = "Jump In",
  ShowMetadata = "Show Metadata",
  HideMetadata = "Hide Metadata",
  ShowWearables = "Show Wearables",
  HideWearables = "Hide Wearables",
  ImageNotFound = "Image Not Found",
  ClickWearable = "Click Wearable",
  ClickProfile = "Click Profile",
  ClickPlace = "Click Place",
  ClickDclLogo = "Click Decentraland Logo",
}
